steps:
  - id: docker build
    name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "europe-north1-docker.pkg.dev/$PROJECT_ID/konttihalli/cloudsql",
        ".",
      ]
  - id: docker push
    name: "gcr.io/cloud-builders/docker"
    args:
      ["push", "europe-north1-docker.pkg.dev/$PROJECT_ID/konttihalli/cloudsql"]
  - id: Deploy to Cloud Run
    name: "gcr.io/cloud-builders/gcloud"
    args:
      - run
      - jobs
      - deploy
      - cloudsqlbackup
      - --image
      - europe-north1-docker.pkg.dev/$PROJECT_ID/konttihalli/cloudsql:latest
      - --region
      - europe-north1 # e.g. us-central1
      - --max-retries
      - "5"
      - --task-timeout
      - 5m

images:
  - europe-north1-docker.pkg.dev/$PROJECT_ID/konttihalli/cloudsql
