main:
  params: [input]
  steps:
    - init:
        assign:
          - projectId: ${sys.get_env("GOOGLE_CLOUD_PROJECT_ID")}
          - instance: ${input.instance}
          - database: ${input.database}
          - bucket: ${input.bucket}
    - startSqlExport:
        call: googleapis.sqladmin.v1beta4.instances.export
        args:
          project: ${projectId}
          instance: ${instance}
          body:
            exportContext:
              fileType: SQL
              uri: ${"gs://" + bucket + "/" + database + ".sql.gz"}
              databases:
                - ${database}
              offload: false
        result: sqlExportOperation
    - checkOperation:
        call: googleapis.sqladmin.v1beta4.operations.get
        args:
          operation: ${sqlExportOperation.name}
          project: ${projectId}
        result: jobStatus
    - checkIfDone:
        switch:
          - condition: ${jobStatus.status == "DONE"}
            next: done
          - condition: ${jobStatus.error}
            raise:
              code: 55
              message: "SQL export operation failed"
          - condition: true
            next: wait
    - wait:
        call: sys.sleep
        args:
          seconds: 5
        next: checkOperation

    - done:
        return: ${jobStatus}
